version: "3.1"

services:
  
  nginx:
    image: php-base
    container_name: web
    ports:
      - "81:8000"
    volumes:
      - path:/var/www/html/
    depends_on:
     - db

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3308:3306"
      - 
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyAdmin
    restart: always
    ports:
      - "82:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_ARBITRARY=db

volumes:
  laravel-mysql:
    driver: local
