version: "3.0"

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "81:8000"
    tty: true  
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/amirreza/docker/www/html/app:/var/www/html/

    environment:
      HTTP_PROXY: 127.0.0.1:10809
      COMPOSE_PROJECT_NAME: mvc
      COMPOSE_PROJECT_HOST: laravel
    networks:
     - test

networks: 
   test:
    driver: bridge
  

volumes:
  html2: {}
  
